### PR TITLE
Text reader fix

### PR DESCRIPTION
**Pull request by stegru**
Made the text reader more reliable, by implementing it in C#

### CODE REVIEW

**Comment by kaspermarkus** [comment]
What's the status of this one @stegru ? Is it still relevant, or?

**Comment by kaspermarkus** [comment]
@stegru is this still relevant?

**Comment by kaspermarkus** [comment]
and if so, can you update?

**Comment by kaspermarkus** [comment]
@stegru ping

**Comment by stegru** [comment]
yes, this needs more work - there are additional requirements.

**Comment by stegru** [comment]
no longer relevant - fixed elsewhere

**Pull request closed without merging**
